"""device_family

Revision ID: 552aa9ec2998
Revises: e49e4f9e791b
Create Date: 2026-09-23 11:00:36.165280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '552aa9ec2998'
down_revision: Union[str, Sequence[str], None] = 'e49e4f9e791b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade ophema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_family', sa.String(length=32), server_default=sa.text("'simulation'"), nullable=False))
    op.create_index('ix_device_family', 'devices', ['device_family'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index("ix_device_family", table_name="devices",)
    op.drop_column("devices", "device_family") 
