"""update device columns

Revision ID: e49e4f9e791b
Revises: ea58679f7e69
Create Date: 2026-09-09 11:58:39.720862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e49e4f9e791b'
down_revision: Union[str, Sequence[str], None] = 'ea58679f7e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        "devices",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )

    op.alter_column(
        "devices",
        "device_type",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=64),
        existing_nullable=False,
    )

    op.alter_column(
        "devices",
        "role",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=32),
        server_default=sa.text("'sensor'"),
        existing_nullable=False,
    )

    op.alter_column(
        "devices",
        "display_name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=128),
        existing_nullable=True,
    )

    op.alter_column(
        "devices",
        "default_config",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        existing_nullable=False,
    )

    op.alter_column(
        "devices",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'default_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('devices', 'display_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('devices', 'role',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('devices', 'device_type',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
